apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-http"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.http.type }}
  ports:
  - port: {{ .Values.service.http.externalPort }}
    targetPort: {{ .Values.service.http.internalPort }}
    protocol: TCP
    name: {{ .Values.service.http.name }}
  selector:
    app: {{ template "fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-rpc"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.rpc.type }}
  ports:
  - port: {{ .Values.service.rpc.externalPort }}
    targetPort: {{ .Values.service.rpc.internalPort }}
    protocol: TCP
    name: {{ .Values.service.rpc.name }}
  selector:
    app: {{ template "fullname" . }}